setlists/urls.py
from django.conf.urls.defaults import *
from django.views.generic import DetailView, ListView
from setlists.models import Setlist, Song
from django.db import models

urlpatterns = patterns('',
    url(r'^$',
        ListView.as_view(
            queryset=Song.objects.annotate(times_used=models.Count('setlist')).order_by('-times_used')[:5],
            context_object_name='most_frequently_used_songs',
            template_name='setlists/index.html')),
    url(r'^all/$',
        ListView.as_view(
            queryset=Setlist.objects.order_by('-date'),
            context_object_name='all_setlists',
            template_name='setlists/all.html')),
    url(r'^setlist/(?P<pk>\d+)/$',
        DetailView.as_view(
            model=Setlist,
            template_name='setlists/setlist.html')),
    url(r'^stats/$',
        ListView.as_view(
            queryset=Song.objects.annotate(times_used=models.Count('setlist'), last_used=models.Max('setlist__date')).order_by('-times_used', '-last_used', 'title'),
            context_object_name='songs',
            template_name='setlists/stats.html')),
)

urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('setlists.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

setlists/models.py
from django.db import models
import datetime

class Song(models.Model):
  title = models.CharField(max_length=200)
  
  def __unicode__(self):
    return self.title
    
  def last_used_date(self):
    if(len(self.setlist_set.all()) > 0):
      return self.setlist_set.aggregate(models.Max('date'))['date__max']
    else:
      return None
    
  def times_used(self):
    return len(self.setlist_set.all())
    
  class Meta:
    ordering = ["title"]

class Setlist(models.Model):
  date = models.DateField()
  title = models.CharField(max_length=200)
  songs = models.ManyToManyField(Song, through='SetlistEntry')
  
  def __unicode__(self):
    return self.title
    
class SetlistEntry(models.Model):
  song = models.ForeignKey(Song)
  setlist = models.ForeignKey(Setlist)
  order = models.PositiveIntegerField()
  
  def __unicode__(self):
    return self.song.title + " in " + self.setlist.title
    
  class Meta:
    ordering = ["order"]

setlists/views.py
# Create your views here.

templates/setlists/all.html
{% extends "setlists/common.html" %}

{% block title %}All Setlists{% endblock %}

{% block nav %}
  <li class="active"><a href="/all">All Setlists</a></li>
{% endblock %}

{% block content %}
  <h2>All Setlists</h2>
  {% if all_setlists %}
    <table class="table table-bordered table-striped">
    <thead><tr><th>Title</th><th>Date</th></tr></thead>
    {% for setlist in all_setlists %}
      <tr><td><a href="/setlist/{{ setlist.id }}">{{ setlist.title }}</a></td><td>{{ setlist.date }}</td></tr>
    {% endfor %}
    </table>
  {% else %}
    <div class="alert alert-warning"><strong>How boring.</strong> No setlists are available.</div>
  {% endif %}
{% endblock %}

templates/setlists/common.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %} {% endblock %} - Setlists</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le styles -->
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="/static/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="images/favicon.ico">
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">

    <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Setlists</a>
          <div class="nav-collapse">
            <ul class="nav">
              {% block nav %}
              <li><a href="/all">All Setlists</a></li>
              {% endblock %}
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      {% block content %}{% endblock %}
      
      <div class="row">
      <div class="span12" style="border-top: 1px solid #ddd; color:#aaa;">
        <p>&copy; 2012 Jonathon Williams.  Built using <a href="http://twitter.github.com/bootstrap/index.html">Bootstrap</a>.</p>
      </div>
      </div>

    </div> <!-- /container -->
    
    

    <!-- Le javascript
    ================================================== -->

    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/static/js/jquery.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>

  </body>
</html>

templates/setlists/index.html
{% extends "setlists/common.html" %}

{% block title %}Home{% endblock %}

{% block content %}
  <div class="row">
    <div class="span8">
      <h1>Sanctuary Setlists</h1>
      <p>Wondering what songs we sang last week at Sanctuary, or which songs
      we've been singing most often?  This site is a repository of all the songs
      Sanctuary has played this year.</p>
    </div>
    <div class="span4">
      <div class="well">
        <h3>Most frequently used songs:</h3>
        {% if most_frequently_used_songs %}
          <ol>
          {% for s in most_frequently_used_songs %}
            <li>{{ s.title }} (used {{ s.times_used }} time{{ s.times_used|pluralize }})</li>
          {% endfor %}
          </ol>
        {% else %}
          <div class="alert alert-warning"><strong>How boring.</strong> No songs are available.</div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

templates/setlists/setlist.html
{% extends "setlists/common.html" %}

{% block title %}{{ setlist.title }}{% endblock %}

{% block nav %}
  <li class="active"><a href="/all">All Setlists</a></li>
{% endblock %}

{% block content %}
  <h2>{{ setlist.title }} on {{ setlist.date }}</h2>
    <ol>
    {% for entry in setlist.setlistentry_set.all %}
      <li>{{ entry.song.title }}</li>
    {% endfor %}
    </ol>
{% endblock %}

templates/setlists/stats.html
{% extends "setlists/common.html" %}

{% block title %}Song Statistics{% endblock %}

{% block nav %}
  <li><a href="/all">All Setlists</a></li>
  <li class="active"><a href="/stats">Song Stats</a></li>
{% endblock %}

{% block content %}
  <h2>Song Statistics</h2>
  {% if songs %}
    <table class="table table-bordered table-striped table-condensed">
    <thead><tr><th>Title</th><th>Number of times used</th><th>Date last used</th></tr></thead>
    <tbody>
    {% for s in songs %}
      <tr><td>{{ s.title }}</td><td>{{ s.times_used }}</td><td>{{ s.last_used_date }}</td></li></tr>
    {% endfor %}
    </tbody>
    </table>
  {% else %}
    <div class="alert alert-warning"><strong>How boring.</strong> No songs are available.</div>
  {% endif %}
{% endblock %}